language: python
python:
  - "2.7"
  - "3.4"
services:
  - mysql
  - postgresql
env:
  - DJANGO=1.4 DB=sqlite
  - DJANGO=1.4 DB=mysql
  - DJANGO=1.4 DB=postgres
  - DJANGO=1.5 DB=sqlite
  - DJANGO=1.5 DB=mysql
  - DJANGO=1.5 DB=postgres
  - DJANGO=1.6 DB=sqlite
  - DJANGO=1.6 DB=mysql
  - DJANGO=1.6 DB=postgres
before_script:
  - mysql -e 'create database aggregation;'
  - psql -c 'create database aggregation;' -U postgres
install:
  - pip install mysql-python
  - pip install psycopg2
  - pip install -q Django==$DJANGO --use-mirrors
script:
  - ./runtests.py -d $DB
